"""
Configuration module for DocStat.
"""

from .settings import (
    SIGNIFICANCE_LEVEL,
    SAMPLE_SIZE_THRESHOLD,
    PLOT_HEIGHT,
    PLOT_WIDTH,
    COLOR_SCHEME,
    CATEGORICAL_PALETTE,
    ALLOWED_EXTENSIONS,
    MAX_FILE_SIZE,
    TEST_TYPES
)

__all__ = [
    'SIGNIFICANCE_LEVEL',
    'SAMPLE_SIZE_THRESHOLD',
    'PLOT_HEIGHT',
    'PLOT_WIDTH',
    'COLOR_SCHEME',
    'CATEGORICAL_PALETTE',
    'ALLOWED_EXTENSIONS',
    'MAX_FILE_SIZE',
    'TEST_TYPES'
] 